language: cpp

sudo: false

compiler:
  - gcc

env:
  global:
    - BUILD_CPR_TESTS=ON
    - GTEST_SHUFFLE=1
    - INSECURE_CURL=ON
    - USE_SYSTEM_CURL=ON
  matrix:
    - COMPILER=g++-4.8 CCOMPILER=gcc-4.8
    - COMPILER=g++-4.9 CCOMPILER=gcc-4.9
    - COMPILER=g++-5 CCOMPILER=gcc-5
    - COMPILER=clang++-3.6 CCOMPILER=clang-3.6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
    packages:
      - g++-4.8
      - g++-4.9
      - g++-5
      - clang-3.6
      - valgrind
      - python-pip
      - python-yaml

install:
  - if [ "$COMPILER" == "g++-4.9" ]; then pip install --user git+git://github.com/eddyxu/cpp-coveralls.git; fi

before_script:
  - export CXX=$COMPILER CC=$CCOMPILER
  - cmake --version
  - mkdir build
  - cd build
  - cmake -LAH ..

script:
  - make VERBOSE=1
  - ctest -V
    
after_success:
  - if [ "$COMPILER" == "g++-4.9" ]; then coveralls -i 'cpr' -i 'include' -e '../include/cpr.h' --root '../' --verbose --gcov-options '\-lp' --gcov 'gcov-4.9'; fi
