version: '1.1.{build}'
configuration:
    - release
os: Visual Studio 2015
before_build:
    - git submodule update --init --recursive
    - set INSECURE_CURL=ON
    - set CMAKE_USE_OPENSSL=OFF
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 14 2015"
build:
    project: C:\projects\cpr\build\cpr.sln
test_script:
    - cd C:\projects\cpr\build
    - ctest -VV -C %Configuration%
